name: pr-ci

on:
  pull_request:
    branches: [main, develop]

jobs:
  pr-ci:
    uses: knallbumm/kb-github-actions/.github/workflows/checks.yml@pnpm
    with:
      # test_check: true
      npm_registry: https://registry.npmjs.org/
