name: Publish new version

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Bump Core Version'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'packages/core'
      
      - name: 'Bump Core Version'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'packages/renderer'

      - name: prepare node
        uses: knallbumm/kb-github-actions/.github/actions/prepare-node@pnpm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}

      - uses: nrwl/nx-set-shas@v3
      - run: pnpm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
